### ISSUE TITLE
Add test cases for diffing changes to types

### ISSUE THREAD

**Issue by shonfeder** [NathanReb/ocaml-api-watch#8] opened 2024-03-06 00:06 UTC
Having a few simple test cases for different API changes would make for a great way to monitor progress on `api-diff` initial implementation.

Add tests that will check the behavior of `api-diff` when

- [ ] Adding a type
- [ ] Removing a type
- [ ] Modifying an existing type

Those tests should be added to `tests/api-diff/run.t`. We can reuse the base `ref.cmi` as the reference interface. For each test case we should generate a new `.mli` file with a change from the list above, compile it to a `.cmi` with `ocamlc` and then run `api-diff ref.cmi <test-file.cmi>`.

You can read about the testing methodology used for the tests at https://github.com/NathanReb/ocaml-api-watch/blob/main/CONTRIBUTING.md#writing-tests

**Comment by MungaSoftwiz** [comment] 2024-03-06 07:31
I love the TDD approach we're taking for this project. I would like to be assigned to this task please.

I'm also kindly requesting for recommendations of resources to learn OCaml and their testing methodology. Thank you.

**Comment by NathanReb** [comment] 2024-03-06 08:53
For OCaml in general I'd recommend the excellent [Real World OCaml](https://dev.realworldocaml.org/). You'll learn plenty about the language and common tools and libraries.

You'll need to learn a bit about dune too so you can take a look at the documentation [here](https://dune.readthedocs.io/en/latest/index.html).

Here we're using dune's cram tests, I explained how they work a bit [here](https://github.com/NathanReb/ocaml-api-watch/blob/main/CONTRIBUTING.md#writing-tests), you can read dune's relevant documentation section [here](https://dune.readthedocs.io/en/latest/tests.html#cram-tests) and you can look at the test we already have in [`tests/api-diff/run.t`](https://github.com/NathanReb/ocaml-api-watch/blob/main/tests/api-diff/run.t) which is the file you'll have to modify to add those test cases.

**Comment by MungaSoftwiz** [comment] 2024-03-06 08:56
Thank you for the awesome collection @NathanReb . I'll be going through the resources to complement the YouTube tutorials I has started.

**Comment by MungaSoftwiz** [comment] 2024-03-06 14:25
I was able to look at the project and this is what I deduced from my understanding.
In this context of API diffing we are referring to changes in module interface. So OCaml exposes types through this interface.
adding: introduction of a new type definition. Extending types that module exposes to the user.
removing: removing type definition from module's interface. Reduces set of exposed types to the users of our API.
modifying: modifying an existing type definition.

So now while adding these tests to verify changes in our API, is it adequate to add tests and only assert it's addition or are there additional considerations to address?

**Comment by NathanReb** [comment] 2024-03-06 18:00
Yes that sums it up pretty well!

> is it adequate to add tests and only expect tests or are there additional considerations to address?

I'm not sure I understand your question but indeed the goal here is to add 3 new tests in the existing `run.t` file that run the tool on `.cmi` files corresponding to interfaces that differs in the ways you just described.

**Comment by MungaSoftwiz** [comment] 2024-03-06 18:03
I was thinking and since we will compare the `ref.mli` then there is no need of including repetitive code of the same. Can we just use the only one present in our Cram tests and add tests for the different files?

**Comment by NathanReb** [comment] 2024-03-06 18:23
Yes that is what the comments at the beginning of the `run.t` file suggest!

**Comment by MungaSoftwiz** [comment] 2024-03-06 19:13
I have a question please. If the dune test shows a type of error that displays plus(+) sign like below. It means I should include that as the error on my tests right?
```
 Now we run api-watcher on the two cmi files, there should be a difference:

   $ api-diff ref.cmi add_type.cmi
-  API changed!
+  api-watcher: CMI argument: no 'add_type.cmi' file or directory
+  Usage: api-watcher [OPTION]… CMI CMI
+  Try 'api-watcher --help' for more information.
+  [124]
```

**Comment by shonfeder** [comment] 2024-03-07 04:01
Hi, @MungaSoftwiz! This is not a typing error, but an error raised by the inability to find the `add_type.cmi` file. Could you please open a draft PR with you current work? This will help us diagnose the problem!

My initial guess is that you may be skipping the step that generates the `.cmi` file, but it will be easier to see once we can look at your code :)

**Comment by MungaSoftwiz** [comment] 2024-03-07 10:55
For the section of remove type can I just remove type by specifying the function to take an argument of any type and not a  specify type?
Because when I try removing it completely it messes up with the function signature and raises an exception.

Like:
```
cat > remove_type.mli <<EOF
val f : 'a -> string
```

**Comment by shonfeder** [comment] 2024-03-07 11:59
Ah, that is a very good question! You've found that in this case we actually cannot remove a type without also changing a value.

I didn't think about that when creating the issue! Your proposed fixes make sense and it is a good way to think about the problem. 

However, since we want the test to be focused on just doing one thing, let's actually change the reference mli so that it includes a type that is not used by any value. Then we can remove *that* and not have to also change the value. This type can just be an alias for `string`, for instance.

Does this make sense?

**Comment by NathanReb** [comment] 2024-03-07 12:00
The problem here is that you'll change something else again and now the diff is that you removed a type and modified `f`.

I suggest updating `ref.mli` instead. It's a bit too simple at the moment and already caused trouble in #17 (cc @Dezzy12).

You'll have to update other places in the test that rely on `ref.mli` being what it currently is but if you're up for it that would be good.

Another simpler solution is to just define you own reference file for this particular test case and we can delay improving the global `ref.mli`.

**Comment by MungaSoftwiz** [comment] 2024-03-07 12:04
I would like to modify the global `ref.mli` to make it incorporate these changes in behaviour. Please if the issue is made assign it to me. @shonfeder @NathanReb

**Comment by NathanReb** [comment] 2024-03-07 12:15
> Would it be okay to just use unit as a placeholder for now

Preferably, no. If you don't want to modify `ref.mli` to keep things simple in this PR then you should use a `type_remove_ref.mli` for this specific test case. Make it a simple `.mli` file with a type and your suggested `f` for instance.

**Comment by MungaSoftwiz** [comment] 2024-03-07 12:19
Okay. Proceeding to modify the original `ref.mli` and the tests that depend on it.

**Comment by MungaSoftwiz** [comment] 2024-03-07 12:36
> Ah, that is a very good question! You've found that in this case we actually cannot remove a type without also changing a value.
> 
> I didn't think about that when creating the issue! Your proposed fixes make sense and it is a good way to think about the problem.
> 
> However, since we want the test to be focused on just doing one thing, let's actually change the reference mli so that it includes a type that is not used by any value. Then we can remove _that_ and not have to also change the value. This type can just be an alias for `string`, for instance.
> 
> Does this make sense?

Yes it does

**Closed** 2024-03-09 16:36 UTC
Labels: good first issue
